### PR TITLE
Add 20 frame acceleration to rats

### PR DESCRIPTION
**Pull request by cxong**
I feel that many of the enemies in this game are too unpredictable because they can instantly change direction, so this is a demo of a solution on the rats: whenever they change direction (in the `compute()` function), they come to a stop (`velocity` 0), then accelerate up to `creatureSpeed` over 20 frames. The effect is subtle but makes them much less dangerous when they change direction:

rataccel

Let me know what you think; perhaps the rats should be sped up to compensate too.

### CODE REVIEW

**Comment by Cirrus-Minor** [comment]
Hi cxong!
I agree with you, I've had for the next release achievements as "complete 1, or 2, or 3 levels without losing HP", and, while playing, I've note how hard that is because the "basic" monsters are very dangerous.
Thanks!

**Comment by cxong** [comment]
After some testing, I've noticed that this change breaks many enemies and has some weird side effects. For example, the pumpkin enemy no longer moves. I'm guessing this is because their `creatureSpeed` is zero? Also, when the player collects good items or opens the boss door, he floats for a bit. Please be aware of these issues.

**Comment by Cirrus-Minor** [comment]
I've initialized the acceleration to 0 in the entity constructor, and that solves the "floating" problem, but for the jumping monsters, as slimes and pumpkins, it doesn't help.
I'm going to conditionate the acceleration physics, I think it's the easier think to do.

**Comment by akien-mga** [comment]
@cxong Nice to see you contributing here :)
Just a git tip, if you update your fork with ```git pull --rebase upstream/dev``` it will get rid of (IMO) useless merge commits like 233257d.

**Comment by cxong** [comment]
@Cirrus-Minor that reminds me; Koji Igarashi once said that the programmer should be able to defeat the enemy without taking a single hit :smile: By the way, will you add the acceleration to the other rats, maybe bats as well?

@akien-mga thanks, I've figured out how using my toolset. It seems that Github wants to assume everyone develops on master and doesn't support this workflow well.

**Comment by Cirrus-Minor** [comment]
Yes Cong, and I've already implemented the bat acceleration.
Btw, you are working on OSX, aren't you?

Hi Akien!

**Pull request merged**
